### ISSUE TITLE
Null Reference on Build

### ISSUE THREAD

**Issue by thomhurst** [sharpliner/sharpliner#213]
Hey, I'm getting this when building the project:

```
  Sharpliner.targets(20, 5): [MSB4018] The "PublishDefinitions" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object.
   at PipelineGenerator.ApiContractTestsPipeline.get_Pipeline() in C:\repo\pipeline\generator\PipelineGenerator\ApiContractTestsPipeline.cs:line 15
   at Sharpliner.AzureDevOps.PipelineDefinitionBase`1.get_Validations()
   at Sharpliner.SharplinerPublisher.Validate(ISharplinerDefinition definition, String typeName)
   at Sharpliner.SharplinerPublisher.PublishDefinition(ISharplinerDefinition definition, Boolean failIfChanged, Type collection)
   at Sharpliner.SharplinerPublisher.Publish(String assemblyPath, Boolean failIfChanged)
```

My pipeline looks like this:

```
using Sharpliner;
using Sharpliner.AzureDevOps;
using Sharpliner.AzureDevOps.Tasks;

namespace PipelineGenerator;

public class ApiContractTestsPipeline : SingleStagePipelineDefinition
{
    private const string Always = "always()";

    public override string TargetFile => Path.Combine("ProfileApi", "pipeline", "azure-pipeline-contract-validation-tests.yml");
    public override TargetPathType TargetPathType => TargetPathType.RelativeToGitRoot;

    public override SingleStagePipeline Pipeline => new()
    {
        Trigger =
        {
            Branches =
            {
                Include = { "develop" }
            }
        },

        Resources = new Resources
        {
            Repositories =
            {
                new(new RepositoryResource("ApiContractsRepo")
                {
                    Name = "Core/MyOtherRepo",
                    Type = RepositoryType.Git
                })
            }
        },

        Variables =
        {
            new(new Variable("ENVIRONMENTNAME", "10")),
            new(new Variable("ENVIRONMENTTYPE", "test")),
            new(new Variable("IS_CONTRACT_TEST_RUN", true)),
            new(new Variable("GitBranchName", variables.Build.SourceBranch)),
            new(new Variable("ApiContractSpecLocation",
                $"{variables.System.DefaultWorkingDirectory}/MyOtherRepo/my-proj/api/my-proj-v2.yaml")),
            new(new Variable("ApiUrl", "https://my-api.example.com")),
        },

        Jobs =
        {
            new Job("RunApiContractTests", "Run API Contract Tests")
            {
                Pool = new Pool("windows-latest"),
                Steps =
                {
                    Checkout.Self,
                    Checkout.Repository("ApiContractsRepo"),

                    DotNet.Restore.Projects("'**/MySolution.AcceptanceTests.csproj") with
                    {
                        NuGetConfigPath = "my-proj-api/nuget.config",
                        DisplayName = "Restore Acceptance Test Packages"
                    },

                    DotNet.Build("'**/MySolution.AcceptanceTests.csproj") with
                    {
                        Arguments = "--configuration Release --no-restore --framework net5.0",
                        DisplayName = "Build Acceptance Tests"
                    },
                    
                    Task("NodeTool@0", "Install Node") with
                    {
                        Inputs = new TaskInputs
                        {
                            { "versionSpec", "14.x" },
                            { "checkLatest", true }
                        }
                    },
                    
                    Script.Inline("npm install -g @stoplight/prism-cli", "Install Prism"),
                    
                    Powershell.File("my-proj-api/ProfileApi/pipeline/RunProxyTests.ps1", "Run Contract Validation Tests") with
                    {
                        Arguments = $"{variables["ApiContractSpecLocation"]} {variables["ApiUrl"]}"
                    },
                    
                    Task("PublishTestResults@2", "Publish Test Results") with
                    {
                        Condition = Always,
                        Inputs = new TaskInputs
                        {
                            { "testResultsFormat", "VSTest" },
                            { "testResultsFiles", "**/*.trx" },
                            { "failTaskOnFailedTests", true },
                            { "testRunTitle", "Contract Validation Tests" },
                        }
                    }
                }
            },
        }
    };
}
```

**Comment by premun** [comment]
Hey @thomhurst,

I quickly checked and it seems (or VS is giving me) null reference assignment in the Trigger. Seems like this should help:
```csharp
        Trigger =
        {
            Branches =
            {
                Include = { "develop" }
            }
        },
```
into this
```csharp
        Trigger = new Trigger("develop"),
```
should do the trick. I will make it so that this doesn't happen.

Meanwhile couple of tips to improve the code:

```csharp
// This
        Variables =
        {
            new(new Variable("ENVIRONMENTNAME", "10")),
            new(new Variable("ENVIRONMENTTYPE", "test")),
            new(new Variable("IS_CONTRACT_TEST_RUN", true)),

// can be turned into this:

        Variables =
        {
            Variable("ENVIRONMENTNAME", "10"),
            Variable("ENVIRONMENTTYPE", "test"),
            Variable("IS_CONTRACT_TEST_RUN", true),
```

Same for the `new()` around the `RepositoryReference`.

Hope this helps and let me know if you have any other issues!

**Comment by thomhurst** [comment]
That fixed it, and thanks for the tips!
