### ISSUE TITLE
Library not found when library is strong-name signed(?)

### ISSUE THREAD

**Issue by premun** [sharpliner/sharpliner#250]
I am getting an error, logging this to have a look later:

```
D:\.nuget\packages\sharpliner\1.4.5\build\Sharpliner.targets(20,5): error MSB4018: The "PublishDefinitions" task failed unexpectedly.
D:\.nuget\packages\sharpliner\1.4.5\build\Sharpliner.targets(20,5): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'Pipelines, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
D:\.nuget\packages\sharpliner\1.4.5\build\Sharpliner.targets(20,5): error MSB4018: File name: 'Pipelines, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
D:\.nuget\packages\sharpliner\1.4.5\build\Sharpliner.targets(20,5): error MSB4018:    at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
D:\.nuget\packages\sharpliner\1.4.5\build\Sharpliner.targets(20,5): error MSB4018:    at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
D:\.nuget\packages\sharpliner\1.4.5\build\Sharpliner.targets(20,5): error MSB4018:    at Sharpliner.SharplinerPublisher.Publish(String assemblyPath, Boolean failIfChanged)
D:\.nuget\packages\sharpliner\1.4.5\build\Sharpliner.targets(20,5): error MSB4018:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
D:\.nuget\packages\sharpliner\1.4.5\build\Sharpliner.targets(20,5): error MSB4018:    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by premun** [comment]
I don't see this anymore
